### ISSUE TITLE
后排提示，关于<style>标签之外的\"

### ISSUE THREAD

**Issue by sumbrez** [FuchsLee/Oxygen_Not_Included-zh#10]
`\"`是转义，就是实际的引号而不是控制用的引号的意思，`<style>`标签内的无疑需要转义，保持不动，标签之外的都是为了显示一个半角引号，所以翻译的话用全角引号即可，不需要在全角引号前加`\`，例如第997和1002行的翻译（有问题）。

**Comment by coldsky2017** [comment]
在这还是说一句吧，我刚遇到有这个问题的句子。
用的是全角双引号。希望跟大家是一样的哦。
