### ISSUE TITLE
当前行号问题

### ISSUE THREAD

**Issue by sumbrez** [FuchsLee/Oxygen_Not_Included-zh#13]
pull时发现有冲突，对比了一下 @FuchsLee 的和我的，发现两处问题：
1. pull冲突的来源应该是 @FuchsLee 第2642行中出现的`\n\n`后“被换行”，导致之后的行号全加1； @coldsky2017 没有这个问题，所以建议是 @FuchsLee 先进行修改；
2. 另一个“比较久远”的问题是，第33行有一个单独的引号，同样是的之后的行号全加1，这个引号在repo的最初版本就有，所以可以等翻译结束后，或者约定下一次commit前统一删去。

**Comment by FuchsLee** [comment]
好的，已经把这两处修改了。
