### ISSUE TITLE
翻译完成

### ISSUE THREAD

**Issue by FuchsLee** [FuchsLee/Oxygen_Not_Included-zh#17]
终于翻译完了，这几天大家辛苦了。
可以先用贴吧的字体注入器进游戏检查一下。
有修改建议可以在这里讨论。

**Comment by coldsky2017** [comment]
游戏刚更新了，貌似支持了unicode。或许能直接用中文了。不过，翻译文件和版本号对不上了啊，怎么直接修改新的.po文件？

**Comment by sumbrez** [comment]
1. 今天的游戏更新后支持大概前8000个unicode，很遗憾不包含中文（最大一块儿中文unicode好像从4xxx开始）。
2. 游戏更新并没有增加新的文本（增加了新的文本的话如果没翻译应该是显示英文，不会导致游戏崩溃什么的）。
2. 即使我用了贴吧的字体注入器也显示不了，操作错了吗？
3. 第6228行多了个空行。

**Comment by coldsky2017** [comment]
所以就是把.po文件的文件头改成最新版本的然后直接覆盖就好了吗？

**Comment by sumbrez** [comment]
什么也不用做

**Comment by FuchsLee** [comment]
我是把ONIFontInjection文件夹放入根目录，然后运行exe就可以了。
