### ISSUE TITLE
关于标点符号

### ISSUE THREAD

**Issue by sumbrez** [FuchsLee/Oxygen_Not_Included-zh#2]
标点符号会使用对应的全角符号，出现在句末的句号也会添加（一开始不准备添加，但是可能会有些连句？所以决定全加上）。

**Comment by FuchsLee** [comment]
嗯，本来有标点的地方换成全角就好，没有的也不必强加吧，除非像是很明显的长句漏了句号。

**Comment by sumbrez** [comment]
我想说的是，对于一些末尾有句号的不长的句子，本来准备翻译的时候不要句号的，当作短句，但想到接下来可能还有句子，所以“翻译出来”，总结一句话就是：尽量保持原文形式和内容。

**Comment by FuchsLee** [comment]
嗯，我也是这么想的。
