### ISSUE TITLE
在“缺氧游戏”吧里发现已经有人提供.po翻译和字体了……

### ISSUE THREAD

**Issue by sumbrez** [FuchsLee/Oxygen_Not_Included-zh#3]

**Comment by FuchsLee** [comment]
好吧，那就弃坑了。辛苦了。

**Comment by beenoera** [comment]
额，我自己还是继续翻，我想做最好的，贴吧里都是机翻和路人翻，非常不可靠。翻完我会发上去贴吧和官帖下面

**Comment by sumbrez** [comment]
机翻啊？我说怎么这么快，估算有5000条语句呢。本来是想在贴吧宣传，找会使git的人的，发现有发布汉化帖子的。

**Comment by FuchsLee** [comment]
看了一下的确很机翻，既然这样我也继续做下去吧。

**Comment by xiaohuang20161012** [comment]
国内有玩家晚上能翻译完整了

**Comment by xiaohuang20161012** [comment]
你们贴吧ID叫什么，一起翻译啊，不要多自己翻译，浪费人力。

**Comment by sumbrez** [comment]
用github一起的话直接在这里交流挺好，贴吧可能比较乱。

**Comment by xiaohuang20161012** [comment]
我不会用这个，我是下载，所以注册的帐号

**Comment by sumbrez** [comment]
看来另一个人也在做，大概一半了。
http://forums.kleientertainment.com/topic/74765-creatingusing-translation-files/?do=findComment&comment=873868

**Comment by coldsky2017** [comment]
为啥我fork到我自己的账号下去再下载下来文件之后用poedit打开，翻译好的文本显示乱码呢？不用管直接接着做没翻译的就好嘛？

**Comment by xiaohuang20161012** [comment]
不够管他继续翻译，在用记事本++修复很快

**Comment by coldsky2017** [comment]
谢谢！
记事本++就是notepad++是吗？

**Comment by xiaohuang20161012** [comment]
晚上有个主播要完整翻译完了，已经翻译剩下1000行，人工翻译，不是机翻

**Comment by xiaohuang20161012** [comment]
是的

**Comment by sumbrez** [comment]
Klei给的pot文件的开头只有
```
"Application: Oxygen Not Included"
"POT Version: 2.0"
```
这种简单信息，而poedit要正确识别显示中文，需要在文件头部添加给poedit用的其他信息。你可以用Klei给的pot在poedit里尝试创建新的翻译，会让你选择语言，选择好后po文件的头部会是
```
 msgid ""
 msgstr ""
 "Project-Id-Version: \n"
 "POT-Creation-Date: \n"
 "PO-Revision-Date: \n"
 "Language-Team: \n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
 "X-Generator: Poedit 1.8.12\n"
 "Last-Translator: \n"
 "Plural-Forms: nplurals=1; plural=0;\n"
 "Language: zh_CN\n"
```
这样poedit可以显示中文。但是为了方便协作，我们需要保持行号固定、统一。（poedit有一个`\n`的小问题在这个repo的其他issue里提到了。）
你可以使用支持utf-8的编辑器打开，直接在`msgstr ""`部分填写翻译就好，最后和poedit编辑出来的其实是一样的。

**Comment by xiaohuang20161012** [comment]
一共就3000多语句

**Comment by coldsky2017** [comment]
这个poedit还没notepad++好用......直接打开就行。
也不知道大家都进行到哪里了。我从第5000行开始吧？

**Comment by xiaohuang20161012** [comment]
用poedit直接翻译就3000行

**Comment by xiaohuang20161012** [comment]
熊猫TV主播在翻译已经剩下1015了。还在翻译

**Comment by coldsky2017** [comment]
嘛，一样的。poedit显示的是一共需要翻译的句子，notpad++显示的是全部代码。反正工作量就那么多。

**Comment by xiaohuang20161012** [comment]
你英文几级了

**Comment by coldsky2017** [comment]
没考级。单词量大概七八千吧。

**Comment by sumbrez** [comment]
第5990行开始的部分或者第7850行开始的`STRINGS.ELEMENTS.*`部分，挑一个“块儿”，有相关性的，尽量不要随便选一行。
你可以再开个issue说一下大概翻译哪一块儿。

**Comment by xiaohuang20161012** [comment]
熊猫TV377910在翻译
建议你们倒着翻译，或直接等晚上他翻译完

**Comment by coldsky2017** [comment]
他弄他的，这东西还是自己做出来的用着舒服。

**Comment by coldsky2017** [comment]
我从5990开始吧。

**Comment by xiaohuang20161012** [comment]
他的翻译质量可以的，顺便问下，你们完成了我可以转游侠吗

**Comment by coldsky2017** [comment]
我个人是不怎么喜欢游侠的......不过我说了也不算，看大家吧。

**Comment by sumbrez** [comment]
README.md文件说明了本repo使用的授权协议，请了解LGPL v2.1协议大概的精神。

**Comment by xiaohuang20161012** [comment]
很多玩家不知道这个网站，嗯，那我不转了
