### ISSUE TITLE
前面部分翻译完了，那我再从8848行的Item 开始了。

### ISSUE THREAD

**Issue by FuchsLee** [FuchsLee/Oxygen_Not_Included-zh#8]

**Comment by coldsky2017** [comment]
我这边直接pull request给你就可以是嘛？

**Comment by FuchsLee** [comment]
是的。

**Comment by coldsky2017** [comment]
pull request的时候只能三个文件全pull过去吗？不懂怎么只选择一个诶。

**Comment by sumbrez** [comment]
那两个文件你不改动就行了

**Comment by coldsky2017** [comment]
あの，咱们要不要做一个名词表啊，毕竟不是一个人来翻译，很多词我发现每个人翻译过来都不一样诶。还有啊，全部翻译完之后要不要做一个staff list写一下每个人完成了哪部分哦？

**Comment by sumbrez** [comment]
1. 可以，可以单独列个文件，但找到标准译名（如果有）或者讨论出一致译名是关键。
2. 可以。

**Comment by coldsky2017** [comment]
名次表可以不急全部文本完成之后查找替换也很快。
每人提交了哪些进度你们能查到就行了。

**Comment by coldsky2017** [comment]
那个，我输入文本的时候，文字和符号都用的全角，没关系的吧？

**Comment by FuchsLee** [comment]
嗯，标点全用全角。

**Comment by coldsky2017** [comment]
不管文字还是标点或者英文字母我都用的全角。

**Comment by FuchsLee** [comment]
文字标点全角，英文半角就可以了。
